/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;
//imports
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.geometry.Insets;

public class App extends Application {
    Stage window;
    Scene scene;
    Button button;
    ComboBox<String> comboBox;

    public static void main(String[] args) {
        launch(args);

    }

    @Override
    public void start(Stage stage) throws Exception {

        IOManager a1 = new IOManager();

        Label label = new Label("Student");

        ObservableList<String> names = FXCollections.observableArrayList("Isaac Griffith", "Bob Sampson", "Sarah James" );

        Label label2 = new Label("Courses");
        ObservableList<String> classes =FXCollections.observableArrayList("CS 1181 Intro to Programming", "CS 2263 Advanced OO Programming", "CS 4423 Software Evolution");

        //Window
        stage = stage;
        ((Stage) window).setTitle("Course View");
        button = new Button("Load Data");
        //Vbox
        VBox layout = new VBox(15);
        layout.setPadding(new Insets(30,30,30,30));
        layout.getChildren().addAll(label, label2 );


        scene = new Scene(layout, 600,  400 );
        stage.setTitle("Homework 2");
        stage.setScene(scene);
        stage.show();


    }

}
